#!/usr/bin/env python3
"""
material_usage_report.py

Reads `shader_report.csv` (generated by scan_material_shaders.py) and searches the
`Assets/` tree for references to the materials. It produces
`material_usage_report.csv` with counts and listing of files that reference each
material. This helps prioritize which materials/shaders to port first.

Usage:
  python tools/material_usage_report.py
"""

import os
import csv
import sys
from collections import defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
ASSETS = os.path.join(ROOT, 'Assets')
INPUT = os.path.join(ROOT, 'shader_report.csv')
OUT = os.path.join(ROOT, 'material_usage_report.csv')

if not os.path.exists(INPUT):
    print('shader_report.csv not found. Run tools/scan_material_shaders.py first.')
    sys.exit(1)

# load materials that have a non-empty shader_asset (we'll prioritize these)
materials = []
with open(INPUT, newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for r in reader:
        mat = r['material']
        shader_asset = r.get('shader_asset','').strip()
        shader_name = r.get('shader_name_text','').strip()
        if shader_asset or shader_name:
            materials.append({
                'material': mat.replace('\\','/'),
                'basename': os.path.basename(mat).lower(),
                'shader_asset': shader_asset.replace('\\','/'),
                'shader_name_text': shader_name
            })

print('Prioritizing {} materials that reference shader assets or have shader name text.'.format(len(materials)))

# search for occurrences of material path or basename in text files under Assets
targets = [m['material'] for m in materials]
basename_map = {m['basename']: m['material'] for m in materials}

occurrences = defaultdict(lambda: {'count':0, 'files':set(), 'shader_asset':'', 'shader_name_text':''})

for dirpath, dirs, files in os.walk(ASSETS):
    for fname in files:
        if fname.endswith(('.unity', '.prefab', '.asset', '.mat', '.controller', '.anim', '.bytes')):
            full = os.path.join(dirpath, fname)
            try:
                with open(full, 'r', encoding='utf-8', errors='ignore') as fh:
                    data = fh.read().lower()
            except Exception:
                continue
            for m in materials:
                mat_lower = m['material'].lower()
                basename = m['basename']
                matched = False
                if mat_lower in data:
                    matched = True
                elif basename in data:
                    # basename matches are noisy but useful
                    matched = True
                if matched:
                    key = m['material']
                    occurrences[key]['count'] += data.count(basename)
                    occurrences[key]['files'].add(os.path.relpath(full, ROOT).replace('\\','/'))
                    occurrences[key]['shader_asset'] = m['shader_asset']
                    occurrences[key]['shader_name_text'] = m['shader_name_text']

# write CSV report
with open(OUT, 'w', newline='', encoding='utf-8') as csvf:
    fieldnames = ['material','shader_asset','shader_name_text','usage_count','referenced_in_files']
    writer = csv.DictWriter(csvf, fieldnames=fieldnames)
    writer.writeheader()
    for mat, info in sorted(occurrences.items(), key=lambda x: -x[1]['count']):
        writer.writerow({
            'material': mat,
            'shader_asset': info.get('shader_asset',''),
            'shader_name_text': info.get('shader_name_text',''),
            'usage_count': info['count'],
            'referenced_in_files': ';'.join(sorted(info['files']))
        })

print('Wrote', OUT)
top = sorted(occurrences.items(), key=lambda x: -x[1]['count'])[:20]
print('Top referenced materials (sample):')
for mat, info in top:
    print(info['count'], mat, '->', info.get('shader_asset') or info.get('shader_name_text'))
